# game settings
RES = WIDTH, HEIGHT = 1600, 900
FPS = 60
SCROLL_SPEED = 8
GRAVITY = 1

# bird settings
BIRD_POS = WIDTH // 4, HEIGHT // 3
BIRD_SCALE = 1.5
BIRD_ANIMATION_TIME = 150
BIRD_JUMP_VALUE = -16
BIRD_JUMP_ANGLE = 25  # deg

# ground
GROUND_HEIGHT = HEIGHT // 12
GROUND_Y = HEIGHT - GROUND_HEIGHT

# pipe settings
PIPE_WIDTH = 250
PIPE_HEIGHT = HEIGHT
DIST_BETWEEN_PIPES = 650
GAP_HEIGHT = 320
HALF_GAP_HEIGHT = GAP_HEIGHT // 2